require 'options'
require 'colors'
require 'keymaps'
require 'plugins'

-- require 'plugin.gruvbox'
require 'plugin.nightfox'
require 'plugin.nvim-tree'
require 'plugin.scrollbar'
require 'plugin.lualine'
require 'plugin.bufferline'
require 'plugin.toggleterm'
require 'plugin.git'
require 'plugin.gitsigns'
require 'plugin.hlslens'
require 'plugin.autopairs'
require 'plugin.telescope'
require 'plugin.mason'
require 'plugin.cmp'
require 'plugin.lspconfig'
require 'plugin.lspsaga'
require 'plugin.lsplines'
require 'plugin.treesitter'
require 'plugin.null-ls'
require 'plugin.telekasten'
require 'plugin.neotest'
